CREATE TABLE IF NOT EXISTS vendors (
    vendorId INT AUTO_INCREMENT PRIMARY KEY,
    vendorName VARCHAR(255),
    businessName VARCHAR(255),
    email VARCHAR(255),
    mobileNumber VARCHAR(255),
    alternateMobileNumber VARCHAR(255),
    addressLine1 VARCHAR(255),
    addressLine2 VARCHAR(255),
    landmark VARCHAR(255),
    city VARCHAR(255),
    district VARCHAR(255),
    state VARCHAR(255),
    pinCode VARCHAR(255),
    gstin VARCHAR(255),
    fssai VARCHAR(255),
    registrationNumber VARCHAR(255),
    aadharNumber VARCHAR(255),
    panNumber VARCHAR(255),
    otherDocuments VARCHAR(255),
    status VARCHAR(255),
    dateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    addedBy VARCHAR(255),
    lastEditedDate TIMESTAMP,
    lastEditedBy VARCHAR(255)
  );