CREATE TABLE IF NOT EXISTS products (
      productId INT AUTO_INCREMENT PRIMARY KEY,
      productName VARCHAR(255),
      category VARCHAR(255),
      measuringUnit VARCHAR(255),
      packSize INT,
      noOfUnits INT,
      unitMRP DECIMAL(10,2),
      packMRP DECIMAL(10,2),
      manufacturer VARCHAR(255),
      marketer VARCHAR(255),
      supplier VARCHAR(255),
      upc VARCHAR(255),
      hsn VARCHAR(255),
      cgst DECIMAL(10,2),
      sgst DECIMAL(10,2),
      igst DECIMAL(10,2),
      cess DECIMAL(10,2),
      loadPrice DECIMAL(10,2),
      unloadingPrice DECIMAL(10,2),
      dateAdded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      addedBy VARCHAR(255),
      lastEditedDate TIMESTAMP,
      lastEditedBy VARCHAR(255)
    );
