CREATE TABLE `inventory` (
	`inventoryId` serial AUTO_INCREMENT NOT NULL,
	`orderedDate` varchar(10),
	`dateOfEntry` varchar(10),
	`referenceNumber` varchar(255),
	`supplier` varchar(255),
	`reason` varchar(255),
	`productId` int,
	`dateOfManufacture` varchar(10),
	`dateOfExpiry` varchar(10),
	`quantity` int,
	`purchasePrice` decimal(10,2),
	`sellingPrice` decimal(10,2),
	`batchNumber` varchar(255),
	`storageLocation` varchar(255),
	`additionalNote` varchar(255),
	`dateAdded` timestamp NOT NULL DEFAULT (now()),
	`addedBy` varchar(255),
	`lastEditedDate` timestamp,
	`lastEditedBy` varchar(255),
	CONSTRAINT `inventory_inventoryId` PRIMARY KEY(`inventoryId`)
);
--> statement-breakpoint
CREATE TABLE `offers` (
	`offerId` serial AUTO_INCREMENT NOT NULL,
	`offerType` varchar(255),
	`offerName` varchar(255),
	`startDate` date,
	`endDate` date,
	`products` varchar(255),
	`offers` varchar(255),
	`discountValue` decimal(10,2),
	`discountPercentage` decimal(10,2),
	`maximumDiscountValue` decimal(10,2),
	`minimumPurchase` decimal(10,2),
	`offerApplicabilityFrequency` varchar(255),
	`applicableTo` varchar(255),
	`status` varchar(255),
	`dateAdded` timestamp NOT NULL DEFAULT (now()),
	`addedBy` varchar(255),
	`lastEditedDate` timestamp,
	`lastEditedBy` varchar(255),
	CONSTRAINT `offers_offerId` PRIMARY KEY(`offerId`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`productId` serial AUTO_INCREMENT NOT NULL,
	`productName` varchar(255),
	`category` varchar(255),
	`measuringUnit` varchar(255),
	`packSize` int,
	`noOfUnits` int,
	`unitMRP` decimal(10,2),
	`packMRP` decimal(10,2),
	`manufacturer` varchar(255),
	`marketer` varchar(255),
	`supplier` varchar(255),
	`upc` varchar(255),
	`hsn` varchar(255),
	`cgst` decimal(10,2),
	`sgst` decimal(10,2),
	`igst` decimal(10,2),
	`cess` decimal(10,2),
	`loadPrice` decimal(10,2),
	`unloadingPrice` decimal(10,2),
	`dateAdded` timestamp NOT NULL DEFAULT (now()),
	`addedBy` varchar(255),
	`lastEditedDate` timestamp,
	`lastEditedBy` varchar(255),
	CONSTRAINT `products_productId` PRIMARY KEY(`productId`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`supplierId` serial AUTO_INCREMENT NOT NULL,
	`supplierName` varchar(255),
	`businessName` varchar(255),
	`mobileNumber` varchar(255),
	`alternateMobileNumber` varchar(255),
	`addressLine1` varchar(255),
	`addressLine2` varchar(255),
	`city` varchar(255),
	`state` varchar(255),
	`pinCode` varchar(255),
	`beneficiaryName` varchar(255),
	`accountNumber` varchar(255),
	`ifscCode` varchar(255),
	`virtualPaymentAddress` varchar(255),
	`remarks` varchar(255),
	`dateAdded` timestamp NOT NULL DEFAULT (now()),
	`addedBy` varchar(255),
	`lastEditedDate` timestamp,
	`lastEditedBy` varchar(255),
	CONSTRAINT `suppliers_supplierId` PRIMARY KEY(`supplierId`)
);
--> statement-breakpoint
CREATE TABLE `transports` (
	`transportId` serial AUTO_INCREMENT NOT NULL,
	`transportName` varchar(255),
	`businessName` varchar(255),
	`vehicleName` varchar(255),
	`email` varchar(255),
	`mobileNumber` varchar(255),
	`alternateMobileNumber` varchar(255),
	`addressLine1` varchar(255),
	`addressLine2` varchar(255),
	`landmark` varchar(255),
	`city` varchar(255),
	`district` varchar(255),
	`state` varchar(255),
	`pinCode` varchar(255),
	`branchOffice` varchar(255),
	`aadharNumber` varchar(255),
	`panNumber` varchar(255),
	`driverName` varchar(255),
	`driverMobileNumber` varchar(255),
	`driverAlternateNumber` varchar(255),
	`status` varchar(255),
	`dateAdded` timestamp NOT NULL DEFAULT (now()),
	`addedBy` varchar(255),
	`lastEditedDate` timestamp,
	`lastEditedBy` varchar(255),
	CONSTRAINT `transports_transportId` PRIMARY KEY(`transportId`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`userId` serial AUTO_INCREMENT,
	`userName` varchar(255),
	`name` varchar(255),
	`mobile` varchar(255),
	`email` varchar(255),
	`role` varchar(255),
	`status` varchar(255),
	`dateAdded` timestamp NOT NULL DEFAULT (now()),
	`addedBy` varchar(255),
	`lastEditedDate` timestamp,
	`lastEditedBy` varchar(255),
	`password` varchar(255)
);
--> statement-breakpoint
CREATE TABLE `vendors` (
	`vendorId` serial AUTO_INCREMENT NOT NULL,
	`vendorName` varchar(255),
	`businessName` varchar(255),
	`email` varchar(255),
	`mobileNumber` varchar(255),
	`alternateMobileNumber` varchar(255),
	`addressLine1` varchar(255),
	`addressLine2` varchar(255),
	`landmark` varchar(255),
	`city` varchar(255),
	`district` varchar(255),
	`state` varchar(255),
	`pinCode` varchar(255),
	`gstin` varchar(255),
	`fssai` varchar(255),
	`registrationNumber` varchar(255),
	`aadharNumber` varchar(255),
	`panNumber` varchar(255),
	`otherDocuments` varchar(255),
	`status` varchar(255),
	`dateAdded` timestamp NOT NULL DEFAULT (now()),
	`addedBy` varchar(255),
	`lastEditedDate` timestamp,
	`lastEditedBy` varchar(255),
	CONSTRAINT `vendors_vendorId` PRIMARY KEY(`vendorId`)
);
--> statement-breakpoint
ALTER TABLE `inventory` ADD CONSTRAINT `inventory_productId_products_productId_fk` FOREIGN KEY (`productId`) REFERENCES `products`(`productId`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `products` ADD CONSTRAINT `products_supplier_suppliers_supplierId_fk` FOREIGN KEY (`supplier`) REFERENCES `suppliers`(`supplierId`) ON DELETE no action ON UPDATE no action;